import streamlit as st
st.set_page_config(page_icon=":cry:", page_title="Dashboard")
st.header("Welcome")
#st.sidebar.success("EntryPoint")
st.subheader("Customer Churn Prediction in Telecom Industry")
st.write("Customer Churn Prediction Building a predictive model for customer churn A Bank wants to take care of customer retention for its product: savings accounts. The bank wants you to identify customers likely to churn balances below the minimum balance. You have the customers information such as age, gender, demographics along with their transactions with the bank. What is the problem? The main problem is to predict if a customer would be credit defaulter or not depending upon the previous data of the customer. Why is it important? It is important from a bank’s perspective in order to maintain business and customer relationship/ Apart from that if someone could be predicted as a defaulter then primitive measures can be taken in order to ensure that such violations do not happen. The ML Pipeline that I have followed is :")
st.markdown("1. Importing the necessary libraries and the dataset")
st.markdown("2. Performing Data Pre-processing (Exploratory Data Analysis and Data Manipulation)")
st.markdown("3. Modelling using Logistic Regression, XGBoost and Random Forest")
st.markdown("4. Performing Prediction")
st.markdown("5. Performing Data Pre-processing (Exploratory Data Analysis and Data Manipulation)")